# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SSH-Expect
version:      1.09
version_from: lib/Net/SSH/Expect.pm
installdirs:  site
requires:
    Expect:                        1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
